### ISSUE TITLE
écran blanc sur MKS ST35 V2 

### ISSUE THREAD

**Issue by vosphil** [makerbase-mks/MKS-Robin-Nano-V1.X#101]
Bonjour, j'ai une carte MKS ROBIN NANO Nano V2, avec un écran MKS ST35V2.
lorsque la carte reboot, âpres avoir mis le firmware "Nano firmware v2.x.x" l'écran reste blanc.
j'ai essayer plusieurs version. mais aucune ne fonctionne .pouvez vous m'aider .
j'ai essayer avec marlin, mais je n'y arrive pas.

merci

**Comment by mks-viva** [comment]
You want to update firmware?
