### ISSUE TITLE
Usb connection problem

### ISSUE THREAD

**Issue by acca84** [makerbase-mks/MKS-Robin-Nano-V1.X#107]
Hello

I have a mks robin nano V1.2 with mks TMC2208 and Marlin.

Last week, i tried to connect the motherboard to pronterface by USB

My printer had a stange behaviour  : 
I was not ablle to connect tom COM port
The hotend started to heat without any reason
The Usb cable seemed to become hot, so i immediately disconnected it and didn't try anymore
One of my TMC2208 stopped working

I don't understand why 
Please help me.

**Comment by mks-viva** [comment]
Please check whether there is a power short circuit problem, such as between USB 5V and GND.
