### ISSUE TITLE
Wiring Pinout v1.3

### ISSUE THREAD

**Issue by LucasvlLima** [makerbase-mks/MKS-Robin-Nano-V1.X#110]
Hello, When we can get the wiring pinout for Robin Nano v1.3?

**Comment by willngton** [comment]
Any update on this request @mks-viva

**Comment by NetoPanto17** [comment]
Any update for robin 1.3 @mks-viva

**Comment by mont2236** [comment]
Also waiting for any update on this robin 1.3 pinout  @mks-viva

**Comment by rafildes** [comment]
Hi, any update for "new" robin 1.3 @mks-viva

**Comment by mks-viva** [comment]
MKS Robin Nano V1.3, MCU is STM32F407VET6, the pinout is same as MKS Robin Nano V1.2_004, only change mcu and firmware.
