### ISSUE TITLE
MKS Robin Nano V1.3

### ISSUE THREAD

**Issue by DonHalkon** [makerbase-mks/MKS-Robin-Nano-V1.X#111]
Does this firmware compatible with MKS Robin Nano V**1.3**? Where can I find documentation for MKS Robin Nano **V1.3**?

**Comment by mks-viva** [comment]
I will upload it.

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/hardware
![image](https://user-images.githubusercontent.com/16629551/132148081-312c7177-73db-41ed-be55-0acad815e32a.png)
