### ISSUE TITLE
Robin nano S 1.3 "font table booting 100%" stuck

### ISSUE THREAD

**Issue by Bergateo** [makerbase-mks/MKS-Robin-Nano-V1.X#116]
Hi everyone! after I've receaved my 3d printer (flyingbear ghost 5) i've tried to upload your marlin firmware but now the board is stuck on that error (font table booting 100%) and doesn't respond or recover after hours of wait... 
Here there the list of the things I've already tried out: 
- to plug off and reinstall the same fw, 
- to install the old one that was working, 
- try another version dowload from an italian repository (but i think it was the same as yours) 
- tried out other different fw 
- format the ft card to fat32 and try again
- tried out different sd cards
But nothing works, the screen stays on the same error.

i think it's a problem in eleborating/reading files in the ft card... 
i would like to try out an arduino or an AVR to force the fw into it or, maybe more simply, to reset to factory data but since i'm not able to do it, i would like to know if is possible and if it is, to kindly have a guide to do it?

**Comment by mks-viva** [comment]
I need close this issues, because has :https://github.com/makerbase-mks/MKS-Robin-Nano-S-Firmware/issues/3
