### ISSUE TITLE
Compiling for Robin Nano35 issue

### ISSUE THREAD

**Issue by imberest** [makerbase-mks/MKS-Robin-Nano-V1.X#14]
Hello, I've been trying to tweak Marlin 2.0 for my needs, but it fails to compile. I've tried stock Marlin 2.0 and it compiles with no problems.
Mks-Robin-Nano-Marlin2.0-Firmware-master gets stuck on:
**Compiling .pio\build\mks_robin_nano35\lib22d\USBComposite\usb_scsi_data.c.o
Compiling .pio\build\mks_robin_nano35\lib22d\USBComposite\usb_setup.cpp.o
Compiling .pio\build\mks_robin_nano35\lib22d\USBComposite\usb_x360.c.o
Archiving .pio\build\mks_robin_nano35\lib22d\libUSBComposite.a
Archiving .pio\build\mks_robin_nano35\lib690\libU8glib-HAL_ID1932.a** <--- stuck...

Tried VS+PlatformIO and tried MKS-Marlin2.0-Compile-Tool so far.

**EDIT**
So, the new release fixed it and I can successfully compile it. The issue I am having is that TFT35 is blank.
Does anyone have any tips or ideas?

All i need is to change stepper drivers to TMC2209_Standalone and FAN pin to PB0 as i shorted PB1 pin...

Problem i am facing is that if i upload _Robin_nano35.bin_ compiled by MKS screen works as normal. Now if i compile **Mks-Robin-Nano-Marlin2.0-Firmware** and upload freshly compiled Robin_nano35.bin to board screen goes blank. Shows only booting message at start.

Also noticed files are different size. Bin provided by MKS 490ish kb and mine is 300kb. 

What should i add to my Config.h file?

**Comment by imberest** [comment]
So, the new release fixed it and I can successfully compile it. The issue I am having is that TFT35 is blank.
Does anyone have any tips or ideas?

**Comment by mks-viva** [comment]
Hi! You can use mks has add UI marlin2.0.5, link：https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware

**Comment by mks-viva** [comment]
Hi! No response, then I will temporarily close this question.
