### ISSUE TITLE
Errors version 2.02

### ISSUE THREAD

**Issue by Engi23** [makerbase-mks/MKS-Robin-Nano-V1.X#25]
1. The second print fails. The printer abuts the carriage against the frame. Rebooting solves the problem.
If you specify G91 in the final code (for example, to move the table down by 10cm corexy), then with the beginning of the second one it will fail. It is decided by the G90 team in the start code. It would be nice if the firmware eliminated such an error.
2. Files in the menu no longer display correctly
1 icon = bmp_custom1
2 icon = bmp_custom1
3 icon = bmp_custom2
4 icon = bmp_custom3
Are they resolved in version 2.03?

**Comment by makerbase-mks** [comment]
We will follow up on this issue
