### ISSUE TITLE
Connection time out error MKS robin nano board

### ISSUE THREAD

**Issue by Jasontwd** [makerbase-mks/MKS-Robin-Nano-V1.X#35]
HI,
After several months of successful prints.
My board is now having connection time out issues and the printer halts mid print after 2 or so hours and waits for commands. I use Octoprint to drive this via Rpi4 and up to date octo firmware.
Ive tried:

1. New USB cables, still same issue
2. Using Slicer to directly communicate to board, still same issue
3. Replaced Rpi4 with new

What else can anyone think this might be??

cheers
jason

**Comment by Miraculix200** [comment]
Tried a lower connection speed yet?

**Comment by makerbase-mks** [comment]
Hi! You can try to change buadrate to 115200.
