### ISSUE TITLE
update the display measurements of the Robin Nano v2

### ISSUE THREAD

**Issue by nictronik99** [makerbase-mks/MKS-Robin-Nano-V1.X#45]
![IMG_20200707_182744](https://user-images.githubusercontent.com/62067513/86812810-b8153a80-c07f-11ea-8d47-cc40f196810e.jpg)
Is it possible to add the measurements I have drawn on the image? They are essential to design a case for the display !!

**Comment by makerbase-mks** [comment]
OK! This you can refer to Robin TFT35, because MKS TS35 only is longer 15mm than MKS Robin TFT35
![image](https://user-images.githubusercontent.com/12979070/86872527-235a1d80-c10f-11ea-974b-6ad1a2480c95.png)

**Comment by mks-viva** [comment]
@nictronik99 https://github.com/makerbase-mks/MKS-TFT-Hardware/blob/master/MKS%20TS35/MKS%20TS35%20V2.0_001/MKS%20TS35%20V2.0_001%20SIZE.DWG
