### ISSUE TITLE
MKS PWC does not work when overheated

### ISSUE THREAD

**Issue by Engi23** [makerbase-mks/MKS-Robin-Nano-V1.X#48]
1. I have MKS PWC and I expected that in an emergency (significant overheating) the board would disconnect itself from the power supply, but this did not happen. Heaters are controlled by transistors. It is well known that transistors often turn on during combustion. With settings.> HEATER_0_MAXTEMP 275 
the temperature went up to 350 degrees, why didn't the board disconnect from the network ?! It is obvious. This is generally the main point of payment - to protect the house from fire!

**Comment by makerbase-mks** [comment]
Hi! Generally speaking, the thermal protection function of marlin can avoid the problem you mentioned.

**Comment by mks-viva** [comment]
@Engi23 Has this problem been solved? I will temporarily close it.
