### ISSUE TITLE
Latest firmware does not work on Robin nano V2

### ISSUE THREAD

**Issue by mgcrea** [makerbase-mks/MKS-Robin-Nano-V1.X#50]
I received an [MKS Robin Nano V2.0 from AliExpress](https://www.aliexpress.com/item/4001185795620.html) that I had to reflash to configure a delta printer (FLSUN Q5).

Did reflash with the latest [Mks_Nano35_V2.0.3.3 Release file.rar](https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/Nano%20firmware%20v2.x.x)

Unfortunately the printer does not work anymore as I have a blank white screen after boot:

![IMG_1788](https://user-images.githubusercontent.com/108273/87817637-99762700-c869-11ea-9e4a-a98f162c4372.jpeg)

What firmware should I upload to have the printer work? Thanks!

**Comment by nictronik99** [comment]
I believe that the only firmware running on Robin nano v2 is currently Marlin-based.

**Comment by mks-viva** [comment]
@mgcrea You can update the lastest firmware and test it, MKS has add a lots of function, include change partmeters by MKS TS35 online
