### ISSUE TITLE
How to add support for MKS servos ?

### ISSUE THREAD

**Issue by themacboy** [makerbase-mks/MKS-Robin-Nano-V1.X#52]
Hello, just purchased 2 MKS-SERVO42A, but Im not sure if they need any special config to be used in Robina Nano v1.2 and Robin Nano v.2

Please if some configs is needed can you explain how to do it in the config file.

Thx in advance !

**Comment by makerbase-mks** [comment]
Hi！ You did not need to change it, you can use it directly.

**Comment by mks-viva** [comment]
@themacboy 
I will close this question temporarily.
