### ISSUE TITLE
MACHINE_PARAMETER what does it do? 

### ISSUE THREAD

**Issue by serdartaylan** [makerbase-mks/MKS-Robin-Nano-V1.X#59]
Hello there,
When I look at the current version V2.0.3.4 discount settings, I saw that such a parameter is MACHINE_PARAMETER.
When I set this value to 1 or 0, I could not understand what convenience or feature it provides.

**Comment by mks-viva** [comment]
Hi!
>MACHINE_PARAMETER		0			#Online parameter(0: disable, 1: enable)
