### ISSUE TITLE
TFT35 screen on Sapphire PRO - Marlin 2

### ISSUE THREAD

**Issue by EG1313** [makerbase-mks/MKS-Robin-Nano-V1.X#6]
Have installed Marlin 2 ("bugfix") on Sapphire Pro and it works fine (board MKS Robin Nano).
Trying to do the same with latest Marlin release (official), ATOM produces the BIN file but as on upload screen goes to 128x64 resolution and so far didn't manage to bring it to 320x240 pixel size.
Upscale x3 - doesn't work, low resolution menu screen with clearly visible items is jammed to upper left corner.

Please help, thanks.
![screen](https://user-images.githubusercontent.com/60331746/73145462-12819680-40f1-11ea-9675-7e191f3e9328.jpg)

**Comment by makerbase-mks** [comment]
I has upload Nano+robin tft35 marlin firmware
![image](https://user-images.githubusercontent.com/12979070/75602045-7b976800-5afc-11ea-82e7-97d6034f99c7.png)

**Comment by EG1313** [comment]
Hello!
my point is - I have succeeded with Marlin 2.0 (bugfix) version but no luck with official releases - any of them. 
For instance I'm trying to get screen "in place" with 2.0.5 and having the same issue.
Permanently low resolution screen gets attached to upper left corner, so called "upscale 3" wont work. 
One more, buttons are working and they are where they are suppose to be but hidden.
Essentially printer is functional but screen...

Appreciate any help on this, thanks!
Attaching my configuration files  

P.S. as well, I can control the printer with any terminal program.


![20200329_132021](https://user-images.githubusercontent.com/60331746/77840420-42691b00-71c2-11ea-9799-6bc3de6fcc69.jpg)
[Marlin_conf.zip](https://github.com/makerbase-mks/MKS-Robin-Nano/files/4398283/Marlin_conf.zip)

**Comment by mks-viva** [comment]
Hi! At present, the latest marlin firmware has fully supported this function. So I will close this question.
