### ISSUE TITLE
 PARAMETER PROBLEM MKS1.2

### ISSUE THREAD

**Issue by Yetreyert** [makerbase-mks/MKS-Robin-Nano-V1.X#60]
I created my firmware by modifying the master firmware that marlin 2.0 that I find on the site, the print works well but the tft35 remains in simple mode. if I try to generate a firmware for tft35 from your tools it doesn't change anything and the words under the icons disappear

**Comment by mks-viva** [comment]
If you use the configuration tool and no text is displayed at the end, then you need to update the font for it.
![image](https://user-images.githubusercontent.com/16629551/96945283-e4aa7080-150f-11eb-9566-650392dfacd6.png)

**Comment by mks-viva** [comment]
I will close this issues temporarily.
