### ISSUE TITLE
firmware robin nano v1.2 tft43

### ISSUE THREAD

**Issue by maalouc** [makerbase-mks/MKS-Robin-Nano-V1.X#62]
Hello, where i can find the firmware or marlin source instructions for mks robin nano v1.2 with a mks 4.3tft!?

**Comment by makerbase-mks** [comment]
Marlin will support Robin TFT43 soon.

**Comment by mks-viva** [comment]
@maalouc 
Hi! I will close this question temporarily.

**Comment by Manfern** [comment]
Is something known with this update? Still not supporting MKS TFT 43?
