### ISSUE TITLE
Uart menu options support

### ISSUE THREAD

**Issue by costelasleontin** [makerbase-mks/MKS-Robin-Nano-V1.X#69]
Will there be options for uart (maybe even spi) in the cfg.txt file to activate and configure it? And be able to activate/deactivate stealthchop from menu, change currents, etc...

**Comment by makerbase-mks** [comment]
Nano V1.2？

**Comment by costelasleontin** [comment]
Oh sorry. Yes it's board is mks Robin nano V1.2 and screen is mks Robin Tft35.

**Comment by makerbase-mks** [comment]
Use it has uart setting: https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware
