### ISSUE TITLE
Random movements during printing due to sd card reading errors

### ISSUE THREAD

**Issue by atomphil** [makerbase-mks/MKS-Robin-Nano-V1.X#7]
I got an issue with the MKS Robin nano v1.1. The print head moves to random locations in the middle of printing, after that printing continues as normal.
I have activated the debugging of the board (M111 S7) and can see that the errors happen randomly when reading from SD card. It is not because of the SD card itself. I have tried different tested cards and different file systems.
At the moment I use vanilla Marlin.

In the change log there is a point:

    2.V1.0.2 Modifications:
    2.1.Fix the bug that read Large capacity sd card data error sometimes.

@makerbase-mks What did you do to fix the read errors?

**Comment by makerbase-mks** [comment]
I modified some card reading functions and changed the types of some of these variables

**Comment by atomphil** [comment]
> 
> 
> I modified some card reading functions and changed the types of some of these variables

What did you changed to make it work better?

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/75978208-fdcac680-5f18-11ea-99e1-254ca648f894.png)
You can change the type of the variable so that it can accommodate a larger address.

**Comment by mks-viva** [comment]
Hi! I will close this question temporarily.
