### ISSUE TITLE
Nano V1.2 on Delta, is it possible?

### ISSUE THREAD

**Issue by pistachin2** [makerbase-mks/MKS-Robin-Nano-V1.X#70]
Hhello everyone, I have a Nano V1.2 mounted on a CoreXY running like a shot.
I have built a homemade Delta, and wanted to know if anyone has this plate mounted on a Delta.
I have my doubts with the endstops, since the delta use the max and this board does not have them implemented, although MKS indicates that it is valid for deltas.
Does anyone have this board mounted on a delta printer?
Any connection suggestions?
Thank you very much.

**Comment by makerbase-mks** [comment]
If use delta, so your X,Y,Z max connect to X Y Z+ endstop

**Comment by pistachin2** [comment]
Hello,
So if I use marlin, the configuration would look like this:
_#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
// # define USE_ZMIN_PLUG // a Z probe
#define USE_XMAX_PLUG
// # define USE_YMAX_PLUG
// # define USE_ZMAX_PLUG_
It is correct or I am wrong.
Thank you very much.

**Comment by mks-viva** [comment]
You can enable all

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
