### ISSUE TITLE
Pause to change color M600

### ISSUE THREAD

**Issue by ivograca** [makerbase-mks/MKS-Robin-Nano-V1.X#71]
M600 dosnt work on any versions of firmware

**Comment by mks-viva** [comment]
Hi! If you use M600 function, so you need enable it.

**Comment by ivograca** [comment]
and how to activate the m600 in the MKS firmware

**Comment by mks-viva** [comment]
Which motherboard and screen do you use?

**Comment by ivograca** [comment]
mks robin nano 1.2 and 3.5 screen in a two trees bluer

mks-viva <notifications@github.com> escreveu no dia quinta, 22/10/2020 à(s)
09:35:

**Comment by mks-viva** [comment]
Which firmware and version do you use?

**Comment by ivograca** [comment]
https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/Nano%20firmware%20v2.x.x
the version is the 2.0.3.4

A quinta, 22/10/2020, 11:50, mks-viva <notifications@github.com> escreveu:

**Comment by mks-viva** [comment]
You need setting it:
1. In robin_nano35_cfg.txt file enable 
```
>MACHINE_PARAMETER		1			#Online parameter(0: disable, 1: enable)
```
2. MKS Robin TFT35: Setting->Machinesettings->Machine->Endstop type->Filament sensor and Open it
3. Your need use fliament sensor connect to MT-DET1 on the motherboard
More information refer to: https://www.youtube.com/watch?v=eubfvnOriuk

**Comment by mks-viva** [comment]
Has this issues be resolved, if there is no response, I will temporarily close it.
