### ISSUE TITLE
How can i make custom boot icon?

### ISSUE THREAD

**Issue by aRTIKa-afk** [makerbase-mks/MKS-Robin-Nano-V1.X#76]
How can i make custom boot pictures? 
i'm using Mks_Nano35_V2.0.3 Release file

**Comment by mks-viva** [comment]
Logo picture?

**Comment by aRTIKa-afk** [comment]
Υep

**Comment by mks-viva** [comment]
1. You need to prepare a 480*320 pictrue and it is bmp format
2. Download [Image2LCD tool](https://github.com/makerbase-mks/Software/blob/master/Image2LCD/Image2Lcd.rar)
3. Run Img2Lcd.exe
4. Open your Logo picture and setting like this:
![image](https://user-images.githubusercontent.com/16629551/98435548-d4e57b80-210e-11eb-90b6-cd7009189eba.png)
5. Save it and name is bmp_logo.bin and replace original bmp_logo.bin file
6. Copy mks_pic folder to TF card and update it.

**Comment by aRTIKa-afk** [comment]
Thx, u r the best
