### ISSUE TITLE
Why does the preview of printing model appear uncorrectly?

### ISSUE THREAD

**Issue by aRTIKa-afk** [makerbase-mks/MKS-Robin-Nano-V1.X#77]
i have some trouble with preview of printing model, i've attached [photo](https://user-images.githubusercontent.com/63347935/98154877-e18b8900-1eee-11eb-98dc-bff47b19e26c.jpg) and [link]( https://yadi.sk/d/GURvAJYd1yDMLw) to gcode for print this model! I hope that u can find solution for this problem!

**Comment by mks-viva** [comment]
You need use the latest mks plug of the cure.
