### ISSUE TITLE
Adding a language

### ISSUE THREAD

**Issue by karohan** [makerbase-mks/MKS-Robin-Nano-V1.X#8]
Hello.

I want to add the language of my country.
I cannot edit the .bin files.
Markerbase Image Editor Does not work properly.

![image](https://user-images.githubusercontent.com/40437087/75193292-fa8c4980-5766-11ea-9c05-d0f1ac9aada0.png)

Can you help me?

**Comment by makerbase-mks** [comment]
Hello, this tool can help you.
https://github.com/makerbase-mks/Software/blob/master/MKS_Image2bin_tool/MKS_Image2bin_tool.rar

**Comment by karohan** [comment]
I know how to make .bmp to.bin files. 
I did not ask you this.
how to add a new language?
Please help me

**Comment by makerbase-mks** [comment]
Hello, there are two ways to add a language:
1. Disable multi-language in the configuration file
> cfg_language_adjust_type 0 # multi-language (enable: 1, disable: 0)
You add your language when designing the picture, and then convert the picture into a .bin file. After updating, you can see the text you designed on the picture.
2. The source code needs to be modified. We have opened the source code for Robin_nano35. You can modify the source code to add your language.

**Comment by karohan** [comment]
hi mks.
I managed to turn the buttons.
where should i translate the articles?
I can't interfere in Chinese writing
All posts, error messages, alerts are in chinese
Please Help me. 

![image](https://user-images.githubusercontent.com/40437087/75396189-fd24a580-5904-11ea-9357-4bdb295a5b5f.png)



![image](https://user-images.githubusercontent.com/40437087/75396113-ca7aad00-5904-11ea-9572-f769a56464ce.png)
![image](https://user-images.githubusercontent.com/40437087/75396130-de261380-5904-11ea-8810-ec4f68fbcb49.png)
![image](https://user-images.githubusercontent.com/40437087/75396155-ebdb9900-5904-11ea-8ebe-2904ae8f420a.png)

**Comment by makerbase-mks** [comment]
The articles supports the following 7 languages, which you can configure in the configuration file. If you want to add other languages, you need to modify the source code:
> cfg_language_type 2 #languages setting, this configuration is valid when "cfg_multiple_language" is disabled.
# (simplified Chinese: 1; traditional Chinese: 2; English: 3; Russian: 4; Spanish: 5; French: 6; Italian: 7).

**Comment by karohan** [comment]
Thank you. Where can I find the source code?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware/tree/1.0.5

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware/tree/1.0.4

**Comment by karohan** [comment]
![image](https://user-images.githubusercontent.com/40437087/75494720-e433f700-59cd-11ea-876a-3cc4c406e0e9.png)
I did not make any changes.
I wanted to test it.
I get this error.
thanks a lot for your support.
All my devices mks <3

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/75940845-17442200-5ec9-11ea-9e9b-a4d070e126ff.png)
Maybe you should open it with this version.

**Comment by karohan** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/40437087/76575579-a3a9a280-64d0-11ea-9c05-cb5c25f289b9.png)



What is the problem?

**Comment by mks-viva** [comment]
Has this problem been resolved?
