### ISSUE TITLE
lights on

### ISSUE THREAD

**Issue by Yetreyert** [makerbase-mks/MKS-Robin-Nano-V1.X#84]
MKS ROBIN NANO 1.2
MARLIN 2.0.6
is it possible to turn a 24v led strip on and off by controlling a pin of the board?

**Comment by mks-viva** [comment]
You can use He1 interface and control led by it

**Comment by Yetreyert** [comment]
is there a tutorial? or what commands should I enter in marlin?

**Comment by mks-viva** [comment]
If your light strip is only powered on, then you can use the He1 interface and use it as an ordinary fan. You can tell me which kind of light strip you use, or provide me with a link

**Comment by mks-viva** [comment]
Hi! Does it work properly? If there is no response, then I will close this issue temporarily.
