### ISSUE TITLE
Make the buzzer sound

### ISSUE THREAD

**Issue by Tony4aro** [makerbase-mks/MKS-Robin-Nano-V1.X#85]
Hi,

I saw the other thread about M300 and possibly adding a speaker.  But I know my Robin Nano V1.2 already has a buzzer.  And, I know it works if the filament out sensor trips.   Is there a way to make it sound at the end of a print?  Is there an M or G to just to turn it on and off?  This is with the factory firmware.  (not Marlin)

**Comment by mks-viva** [comment]
Hi! I'm sorry, this is not possible.
