### ISSUE TITLE
5V power

### ISSUE THREAD

**Issue by Adi146** [makerbase-mks/MKS-Robin-Nano-V1.X#87]
Hi, is it possible to power the Makerbase Robin Nano V1.2 over a 5V Pin? Like you can power it over USB but over one of the GPIO Pins?

**Comment by mks-viva** [comment]
Select power DC5V or USB‘s 5V by jupmers？

**Comment by Adi146** [comment]
Yes but which Pins do I have to use for 5V and Ground? Can it be any 5V and Ground?

**Comment by mks-viva** [comment]
MKS Robin Nano V1.2 has add USB 5V power select
