### ISSUE TITLE
PB0 and PB1 pins stopped working

### ISSUE THREAD

**Issue by Bobby-McBobface** [makerbase-mks/MKS-Robin-Nano-V1.X#91]
I am using MKS Robin Nano V1.2.
I tried to turn on the fans, but it didn't work. 
The fans worked before; they suddenly stopped working.
The fans are working; I probed the PB0 and PB1 pins and they weren't giving out a voltage.
Everything else is working.
I did not update any firmware.

Is my board broken or is this a software issue?

**Comment by mks-viva** [comment]
You need check the board is work or is kill by USB connect to pc?

**Comment by Bobby-McBobface** [comment]
I found out one of the pins on the board was bent. I have fixed it. Thank you for your help
